# Generated by Django 4.2.7 on 2023-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='education.course'),
        ),
    ]
