# Generated by Django 4.2.7 on 2023-12-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Título')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('url', models.URLField(verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Link',
                'ordering': ['-created'],
            },
        ),
    ]
